# -*- coding: utf-8 -*-
"""Sei-framework

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ui2d9Tlw31we052um_zomP8hmhVXneTb
"""

from google.colab import drive
drive.mount('/content/drive')

#NOT
!wget -qO ac.sh https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh
!bash ac.sh -bfp /usr/local

!conda create --yes --name Manuel

!conda init Manuel

!pip install torch torchvision

!pip install selene-sdk

!git clone https://github.com/FunctionLab/sei-framework

!pip install docopt

!wget https://zenodo.org/record/4906997/files/sei_model.tar.gz

!tar -xzvf sei_model.tar.gz

# Sei framework resources (FASTA files)
!wget https://zenodo.org/record/4906962/files/sei_framework_resources.tar.gz

!tar -xzvf sei_framework_resources.tar.gz

!python /content/sei-framework/1_variant_effect_prediction.py -h

!python /content/sei-framework/1_variant_effect_prediction.py /content/drive/MyDrive/BimaProject/Galaxy10-[MiModD_VCF_Filter_on_data_2].vcf /content/drive/MyDrive/BimaProject/Modig1/Test3 --genome=hg38 --cuda

!python /content/sei-framework/2_varianteffect_sc_score.py /content/drive/MyDrive/BimaProject/Modig1/chromatin-profiles-hdf5/Filtered.ref_predictions.h5 /content/drive/MyDrive/BimaProject/Modig1/chromatin-profiles-hdf5/Filtered.alt_predictions.h5 /content/drive/MyDrive/BimaProject/Modig1//chromatin-profiles-hdf5

!python /content/sei-framework/2_varianteffect_sc_score.py -h

"""# New Section"""